[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA-style fallback so client-side routes work in production
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
